import "./globals.css"
export const metadata = {
title: 'Walmart | Clone',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="container mx-auto">{children}</body>
    </html>
  )
}
